name: Run specific e2e tag

on:
  workflow_dispatch:
    inputs:
      useExistingTag:
        required: true
        type: boolean
        description: "Use existing tag"
        default: true
      newTag:
        description: "Use new tag to run"
        required: false
      existingTag:
        type: choice
        required: true
        description: Choose the tag in the list
        options:
          - smoke.test
          - database
          - dashboard
          - apis
          - project
          - sign
          - localization
        default: smoke.test

jobs:
  rune2e:
    name: Run e2e tag
    runs-on: ubuntu-latest

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install

      - name: Run test for new newTag
        if: ${{ !github.event.inputs.useExistingTag }}
        run: npm run test:headless:tag "@${{ github.event.inputs.newTag }}"

      - name: Run test for new existingTag
        if: ${{ github.event.inputs.useExistingTag }}
        run: npm run test:headless:tag "@${{ github.event.inputs.existingTag }}"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: error
          retention-days: 1
      - name: Upload a screenshot
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: screenshot
          path: screenshot
          if-no-files-found: error
          retention-days: 1
