name: Run e2e Jitera staging daily

on:
  workflow_dispatch:
  # schedule:
    # - cron: "0 18 * * *" #Run for 3AM JST every day
    # - cron: "0 5 * * 0-4" #Run for 12AM JST every weekday Mon-Fri
    # - cron: "0 */8 * * 1-4" #Run every 8-hours Mon-Fri
    # - cron: "0 */12 * * 5-6" #Run every 12-hours Sat-Sun

jobs:
  rune2e:
    name: Run e2e
    runs-on: ubuntu-latest

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera-Product/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm run compile-canvas && npm install
      - run: export ACC_JITERA_E2E=staging_tester1 && npm run test:staging
      - name: Run test for API
        if: always()
        run: export ACC_JITERA_E2E=staging_tester1 && export API_RUNNER=true && npm run test:headless:api
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
      - name: Upload a screenshot
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: screenshot
          path: screenshot
          retention-days: 1
      - name: Upload rerun list
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: output
          path: output
          retention-days: 1

  rerun-failed-e2e:
    if: ${{ always() }}
    needs: rune2e
    name: Re-run failed e2e
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera-Product/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/download-artifact@v3
        with:
          name: output
          path: output
      - run: npm run compile-canvas && npm install
      - run: export ACC_JITERA_E2E=staging_tester1 && sh rerun.sh
      - name: Re-run test for API
        if: always()
        run: export ACC_JITERA_E2E=staging_tester1 && yarn clsresultjs && sh rerunApi.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
      - name: Upload rerun output
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: output-rerun
          path: output
          retention-days: 1

  exporting-e2e:
    if: ${{ always() }}
    needs: rerun-failed-e2e
    name: Run e2e exporting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        suite: [1, 2, 3]

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera-Product/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm run compile-canvas && npm install
      - run: export ACC_JITERA_E2E=staging_tester1 && npm run test:headless:exporting "@export.${{ matrix.suite }}"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 5
      - name: Upload exporting output
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: output-exporting
          path: output
          retention-days: 1

  rerun-exporting:
    if: ${{ always() }}
    needs: exporting-e2e
    name: Rerun failed exporting
    runs-on: ubuntu-latest

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera-Product/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm run compile-canvas && npm install
      - run: export ACC_JITERA_E2E=staging_tester1 && export EXPORT_E2E=true && sh rerunSpecificWorker.sh 1
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 5
      - name: Upload exporting output
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: output-rerun-exporting
          path: output
          retention-days: 1

  e2e-preview:
    if: ${{ always() }}
    needs: rerun-exporting
    name: Run preview e2e
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera-Product/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm run compile-canvas && npm install
      - run: export ACC_JITERA_E2E=staging_tester1 && npm run test:headless:preview
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
      - name: Upload rerun output
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: output-preview
          path: output
          retention-days: 1
      - name: Upload e2e download
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: e2e-download-log
          path: e2e-download/*.log
          retention-days: 1

  set-status-e2e:
    if: ${{ always() }}
    needs: e2e-preview
    name: Set status of e2e
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: output-rerun
          path: output-rerun
      - uses: actions/download-artifact@v3
        with:
          name: output-exporting
          path: output-exporting
      - uses: actions/download-artifact@v3
        with:
          name: output-preview
          path: output-preview
      - run: |
          out_rerun='./output-rerun/failed-specs-to-rerun.txt'
          api_out_rerun='./output-rerun/api-failed-specs-to-rerun.txt'
          out_exporting='./output-exporting/failed-specs-to-rerun.txt'
          out_rerun_exporting='./output-rerun-exporting/failed-specs-to-rerun.txt'
          out_preview='./output-preview/failed-specs-to-rerun.txt'

          if [ -s $out_rerun ] || [ -s $api_out_rerun ] || [ -s $out_exporting ] || [ -s $out_rerun_exporting ] || [ -s $out_preview ]
          then
              echo "Status of rerun job is FAILED!!!"
              exit 1
          fi

  ghpagee2e:
    if: ${{ always() }}
    needs: e2e-preview
    name: Generate report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 30

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  slack:
    name: Slack Notification
    if: ${{ always() }}
    needs: ghpagee2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sleep 300

      - name: Slack Notification for pass run
        if: ${{ always() && contains(join(needs.set-status-e2e.result, ','), 'success') }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: jitera_e2e_bot
          SLACK_COLOR: ${{needs.set-status-e2e.result}}
          SLACK_ICON_EMOJI: ":jitera:"
          SLACK_MESSAGE: |
            Description:
            - Run all test for Database, API, Dashboard, Mobile, Web,...
            - Run exporting for new project
            - Run exporting for existing project: DONOTUSE_E2E_EXPORTING1Z, E2E_JUMP_TEAM_EXPORTING_DO_NOT_USE

            GREAT!!! NO ACTION TO DO 🍀🍀🍀
          SLACK_TITLE: ✅✅✅ Run REGRESSION check for STAGING env with status ${{needs.set-status-e2e.result}} 🚀🚀🚀
          SLACK_USERNAME: E2E-BOT-STAGING-REGRESSION
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: Jitera e2e Staging Regression
          MSG_MINIMAL: true
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: jitera_e2e_internal_bot
          SLACK_COLOR: ${{needs.set-status-e2e.result}}
          SLACK_ICON_EMOJI: ":jitera:"
          SLACK_MESSAGE: |
            Description:
            - Run all test for Database, API, Dashboard, Mobile, Web,...
            - Run exporting for new project
            - Run exporting for existing project: DONOTUSE_E2E_EXPORTING1Z, E2E_JUMP_TEAM_EXPORTING_DO_NOT_USE

            Please visit report at: https://levinhgithub.github.io/test-github-action/${{ github.run_number }}/
          SLACK_TITLE: ✅✅✅ Run REGRESSION check for STAGING env with status ${{needs.set-status-e2e.result}} 🚀🚀🚀
          SLACK_USERNAME: E2E-BOT-STAGING-REGRESSION
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: Jitera e2e Staging Regression

