name: Run e2e Jitera staging daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * 1-4" #Run for 3AM JST every weekday Mon-Fri
    - cron: "0 */12 * * 5-6" #Run for 3AM JST every weekday Sat-Sun
    # - cron: "0 18 * * 0-4" #Run for 3AM JST every weekday Mon-Fri

jobs:
  rune2e:
    name: Run e2e
    runs-on: ubuntu-latest

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run test:staging
      - name: Run test for API
        if: always()
        run: export API_RUNNER=true && npm run test:headless:api
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
      - name: Upload a screenshot
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: screenshot
          path: screenshot
          retention-days: 1
      - name: Upload rerun list
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: output
          path: output
          retention-days: 1

  rerun-failed-e2e:
    if: ${{ always() }}
    needs: rune2e
    name: Re-run failed e2e
    runs-on: ubuntu-latest

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results
      - uses: actions/download-artifact@v3
        with:
          name: output
          path: output
      - run: npm install
      - run: sh rerun.sh
      - name: Re-run test for API
        if: always()
        run: sh rerunApi.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  exporting-e2e:
    if: ${{ always() }}
    needs: rerun-failed-e2e
    name: Run e2e exporting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        suite: [1,2,3]

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout jitera_e2e_revamp repo
        uses: actions/checkout@v2
        with:
          repository: Jitera/jitera_e2e_revamp
          fetch-depth: "0"
          ref: develop
          token: ${{ secrets.PAT }}
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run test:headless:exporting "@export.${{ matrix.suite }}"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 5
  
  ghpagee2e:
    if: ${{ always() }}
    needs: exporting-e2e
    name: Generate report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 30

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  slack:
    name: Slack Notification
    if: ${{ always() }}
    needs: [ghpagee2e,rerun-failed-e2e,exporting-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: jitera_e2e_bot
          SLACK_COLOR: ${{needs.rerun-failed-e2e.result && needs.exporting-e2e.result}}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: |
            - Please wait 5mins and follow this link to see the report: https://levinhgithub.github.io/test-github-action/${{ github.run_number }}/
            Note: Follow this link to know how to use the artifact https://bit.ly/2XYWEFs at section "How to use the Artifact to debug the e2e test"
          SLACK_TITLE: Status
          SLACK_USERNAME: E2E-JITERA-BOT
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: Jitera e2e revamp
