# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run e2e CI

on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]
  

jobs:
  e2e-localci:
    name: Run e2e
    runs-on: ubuntu-latest
    if: ${{ (github.event.review.state == 'approved') && (contains(github.event.pull_request.labels.*.name, 'test')) }}
    
    steps:
    - uses: browser-actions/setup-chrome@latest
    - run: echo ""
